# Generated by Django 2.2.4 on 2020-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('score', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
