# Generated by Django 2.2.4 on 2020-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlcon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField(auto_now=True)),
            ],
        ),
    ]
