# Generated by Django 2.2.4 on 2019-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepost',
            fields=[
                ('banner', models.ImageField(default='', upload_to='hub/images')),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=50000)),
            ],
        ),
    ]
