# Generated by Django 2.2.4 on 2019-12-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepost',
            name='head0',
        ),
        migrations.AlterField(
            model_name='homepost',
            name='title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
