# Generated by Django 2.2.4 on 2019-12-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_homepost_chead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('chead', models.CharField(default='', max_length=50000)),
                ('image', models.ImageField(default='', upload_to='hub/image')),
            ],
        ),
    ]
