# Generated by Django 2.2.4 on 2019-12-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='id',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='post_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
